services:
  mongo:
    image: mongo
    container_name: anon_messageboard_mongo_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: messages
    volumes:
      - messages_prod:/data/db
  backend:
    image: anon_messageboard_backend_prod
    container_name: anon_messageboard_backend_prod
    build:
      context: ./backend
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:example@mongo:27017
      NODE_ENV: production
    depends_on:
      - mongo
  frontend:
    image: anon_messageboard_frontend_prod
    container_name: anon_messageboard_frontend_prod
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    depends_on:
      - backend
  nginx:
    image: nginx:1.20.1
    container_name: anon_messageboard_nginx_prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend

volumes:
  messages_prod:

## TODO
# - ROute requests from frontend to backend via a proxy url '/api'
