services:
  mongo:
    image: mongo
    container_name: anon_messageboard_mongo_dev
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: messages
    volumes:
      - messages:/data/db
  backend:
    image: anon_messageboard_backend_dev
    container_name: anon_messageboard_backend_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:example@mongo:27017
volumes:
  messages:
