version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Munaf-Divan"
    reviewers:
      - "kalpesh3000"
    labels:
      - "dependencies"
      - "dependabot"
      